version: '2.3'

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./regdata:/regdata
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/regdata
